#SERVER
HOST: "0.0.0.0"
PORT: 5000
DEBUG: True
#LIMIT
LOWER_LIMIT_FOR_CACHING: 10000
CACHE_ENABLE: True
CACHING_UPPER_LIMIT: 60000
CACHE_DIRECTORY: "cache/"
#API Specific
API_VERSION: "v1"
API_ENDPOINT: "fibonacci/get"
#MESSAGES
CACHE_LIMIT_EXCEEDED_ERROR: "You have exceeded the cache threshold of this system. Please ask the admin to increase the threshold to proceed."
NEGATIVE_VALUE_ERROR: "Please enter positive integer values to get desired output"
DEFAULT_TITLE: "Message"
DEFAULT_MESSAGE: "Welcome! You have reached the default page"
EXCEPTION_TITLE: "Exception"
SUCCESS_TITLE: "results"
FORBIDDEN_ERROR: "This method is forbidden"
NUMERIC_ONLY_ERROR: "Please provide number of elements to be generated. Refer API doc"
#STATUSCODES
STATUSCODE_TITLE: "status_code"
NEGATIVE_CODE: 400
SUCCESS_CODE: 200
FORBIDDEN_CODE: 405
CACHE_LIMIT_EXCEEDED_CODE: 414
